Add checks that dependencies exist

diff --git a/git-d8mr b/git-d8mr
--- a/git-d8mr
+++ b/git-d8mr
@@ -18,6 +18,16 @@ if [[ ! "$TYPE" =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|tas
   exit 1
 fi
 
+if ! command -v jq &>/dev/null; then
+  echo "Error: jq is required but not installed. https://jqlang.org/download/"
+  exit 1
+fi
+
+if ! command -v curl &>/dev/null; then
+  echo "Error: curl is required but not installed."
+  exit 1
+fi
+
 MR=$2
 PROJECT=$(curl --silent https://git.drupalcode.org/api/v4/projects/project%2Fdrupal/merge_requests/${MR} | jq -r .source_project_id)
 ISSUE=$(curl --silent https://git.drupalcode.org/api/v4/projects/${PROJECT} | jq -r .path | cut -d- -f2)
